on:
  push:
    branches:
      - "master"

jobs:
  pull_request:
    if: github.repository == 'HealthTap/doorkeeper-device_authorization_grant'
    name: Back Merge Branches
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Back Merge Branches
        run: ruby scripts/git_back_merge.rb ${{github.token}} ${{secrets.SECONDARY_TOKEN}} ${{secrets.SLACK_WEBHOOK_URL}}
